//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.proto
namespace Nuctech.NIS.Common.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHeader")]
  public partial class MsgHeader : global::ProtoBuf.IExtensible
  {
    public MsgHeader() {}
    
    private string _src;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"src", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string src
    {
      get { return _src; }
      set { _src = value; }
    }
    private double _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}