//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: device_common.proto
// Note: requires additional types generated from: common.proto
namespace Nuctech.NIS.Common.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SG_DeviceCommonParamMsg")]
  public partial class SG_DeviceCommonParamMsg : global::ProtoBuf.IExtensible
  {
    public SG_DeviceCommonParamMsg() {}
    
    private MsgHeader _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MsgHeader header
    {
      get { return _header; }
      set { _header = value; }
    }
    private uint _heartbeat_timeout = (uint)5;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heartbeat_timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)5)]
    public uint heartbeat_timeout
    {
      get { return _heartbeat_timeout; }
      set { _heartbeat_timeout = value; }
    }
    private uint _heartbeat_interval = (uint)5;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"heartbeat_interval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)5)]
    public uint heartbeat_interval
    {
      get { return _heartbeat_interval; }
      set { _heartbeat_interval = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SG_DeviceStoreParamMsg")]
  public partial class SG_DeviceStoreParamMsg : global::ProtoBuf.IExtensible
  {
    public SG_DeviceStoreParamMsg() {}
    
    private MsgHeader _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MsgHeader header
    {
      get { return _header; }
      set { _header = value; }
    }
    private string _image_upload_path;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"image_upload_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string image_upload_path
    {
      get { return _image_upload_path; }
      set { _image_upload_path = value; }
    }
    private OfflineUploadOrderType _offline_upload_order = OfflineUploadOrderType.OldestFirst;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"offline_upload_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(OfflineUploadOrderType.OldestFirst)]
    public OfflineUploadOrderType offline_upload_order
    {
      get { return _offline_upload_order; }
      set { _offline_upload_order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SG_DeviceInfoChangeMsg")]
  public partial class SG_DeviceInfoChangeMsg : global::ProtoBuf.IExtensible
  {
    public SG_DeviceInfoChangeMsg() {}
    
    private MsgHeader _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MsgHeader header
    {
      get { return _header; }
      set { _header = value; }
    }
    private string _device_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _device_position;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"device_position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_position
    {
      get { return _device_position; }
      set { _device_position = value; }
    }
    private string _image_upload_path;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"image_upload_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string image_upload_path
    {
      get { return _image_upload_path; }
      set { _image_upload_path = value; }
    }
    private string _device_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"device_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_name
    {
      get { return _device_name; }
      set { _device_name = value; }
    }
    private string _device_tunnel = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"device_tunnel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_tunnel
    {
      get { return _device_tunnel; }
      set { _device_tunnel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SG_UploadPassRecordMsg")]
  public partial class SG_UploadPassRecordMsg : global::ProtoBuf.IExtensible
  {
    public SG_UploadPassRecordMsg() {}
    
    private MsgHeader _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MsgHeader header
    {
      get { return _header; }
      set { _header = value; }
    }
    private string _device_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _record_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"record_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string record_id
    {
      get { return _record_id; }
      set { _record_id = value; }
    }
    private uint _device_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"device_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint device_type
    {
      get { return _device_type; }
      set { _device_type = value; }
    }
    private string _pass_result;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pass_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pass_result
    {
      get { return _pass_result; }
      set { _pass_result = value; }
    }
    private double _start_time;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }
    private double _end_time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private string _certificate_photo = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"certificate_photo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string certificate_photo
    {
      get { return _certificate_photo; }
      set { _certificate_photo = value; }
    }
    private string _face_photo = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"face_photo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string face_photo
    {
      get { return _face_photo; }
      set { _face_photo = value; }
    }
    private SG_UploadPassRecordMsg.PassResultType _risk_level = SG_UploadPassRecordMsg.PassResultType.NORMAL;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"risk_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SG_UploadPassRecordMsg.PassResultType.NORMAL)]
    public SG_UploadPassRecordMsg.PassResultType risk_level
    {
      get { return _risk_level; }
      set { _risk_level = value; }
    }
    private SG_UploadPassRecordMsg.CertificateType _certificate_type;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"certificate_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SG_UploadPassRecordMsg.CertificateType certificate_type
    {
      get { return _certificate_type; }
      set { _certificate_type = value; }
    }
    private uint _certificate_no = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"certificate_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint certificate_no
    {
      get { return _certificate_no; }
      set { _certificate_no = value; }
    }
    private uint _certificate_period = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"certificate_period", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint certificate_period
    {
      get { return _certificate_period; }
      set { _certificate_period = value; }
    }
    private uint _passenger_name = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"passenger_name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint passenger_name
    {
      get { return _passenger_name; }
      set { _passenger_name = value; }
    }
    private string _compare_result = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"compare_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string compare_result
    {
      get { return _compare_result; }
      set { _compare_result = value; }
    }
    private string _risk_control = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"risk_control", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string risk_control
    {
      get { return _risk_control; }
      set { _risk_control = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PassResultType")]
    public enum PassResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORMAL", Value=0)]
      NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FACENOTFOUND", Value=1)]
      FACENOTFOUND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPAREFAILED", Value=2)]
      COMPAREFAILED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MULTIPLEFACE", Value=3)]
      MULTIPLEFACE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RISKPERSON", Value=4)]
      RISKPERSON = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CertificateType")]
    public enum CertificateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSPORT", Value=0)]
      PASSPORT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IDCARD", Value=1)]
      IDCARD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ICCARD", Value=2)]
      ICCARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOARDINGPASS", Value=3)]
      BOARDINGPASS = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SG_UploadPassRecorEchodMsg")]
  public partial class SG_UploadPassRecorEchodMsg : global::ProtoBuf.IExtensible
  {
    public SG_UploadPassRecorEchodMsg() {}
    
    private MsgHeader _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MsgHeader header
    {
      get { return _header; }
      set { _header = value; }
    }
    private string _record_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"record_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string record_id
    {
      get { return _record_id; }
      set { _record_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"OfflineUploadOrderType")]
    public enum OfflineUploadOrderType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OldestFirst", Value=0)]
      OldestFirst = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewestFirst", Value=1)]
      NewestFirst = 1
    }
  
}