//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: device_auth.proto
// Note: requires additional types generated from: common.proto
namespace Nuctech.NIS.Common.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SG_DeviceEventLogMsg")]
  public partial class SG_DeviceEventLogMsg : global::ProtoBuf.IExtensible
  {
    public SG_DeviceEventLogMsg() {}
    
    private MsgHeader _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MsgHeader header
    {
      get { return _header; }
      set { _header = value; }
    }
    private string _device_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private DeviceEventType _event_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"event_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DeviceEventType event_id
    {
      get { return _event_id; }
      set { _event_id = value; }
    }
    private double _event_start_time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"event_start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double event_start_time
    {
      get { return _event_start_time; }
      set { _event_start_time = value; }
    }
    private byte[] _description = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] description
    {
      get { return _description; }
      set { _description = value; }
    }
    private EventLevel _event_level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"event_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EventLevel event_level
    {
      get { return _event_level; }
      set { _event_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EventLevel")]
    public enum EventLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INFO", Value=1)]
      INFO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KEY", Value=2)]
      KEY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WARN", Value=3)]
      WARN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_LEVEL", Value=4)]
      ERROR_LEVEL = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DeviceEventType")]
    public enum DeviceEventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"POWER_ON", Value=1)]
      POWER_ON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POWER_OFF", Value=2)]
      POWER_OFF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VERIFICATION_FAILURE", Value=3)]
      VERIFICATION_FAILURE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE", Value=4)]
      UPDATE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER_OPERATION", Value=5)]
      OTHER_OPERATION = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAULT", Value=6)]
      FAULT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAULT_RECOVERY", Value=7)]
      FAULT_RECOVERY = 7
    }
  
}